# Change these first
owner: ajainvivek # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: DocPile CORE API
    url: https://api.docpile.io/healthcheck
  - name: DocPile Account
    url: https://account.docpile.io/register

